// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GetParametersTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "GetParametersTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "GetParameters.hpp"

#include "ParameterValue.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace rcl_interfaces {
namespace srv {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_GetParameters_Request_type_identifier(
        TypeIdentifierPair& type_ids_GetParameters_Request)
{

    ReturnCode_t return_code_GetParameters_Request {eprosima::fastdds::dds::RETCODE_OK};
    return_code_GetParameters_Request =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "rcl_interfaces::srv::GetParameters_Request", type_ids_GetParameters_Request);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_GetParameters_Request)
    {
        StructTypeFlag struct_flags_GetParameters_Request = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_GetParameters_Request = "rcl_interfaces::srv::GetParameters_Request";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_GetParameters_Request;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_GetParameters_Request;
        CompleteTypeDetail detail_GetParameters_Request = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_GetParameters_Request, ann_custom_GetParameters_Request, type_name_GetParameters_Request.to_string());
        CompleteStructHeader header_GetParameters_Request;
        header_GetParameters_Request = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_GetParameters_Request);
        CompleteStructMemberSeq member_seq_GetParameters_Request;
        {
            TypeIdentifierPair type_ids_names;
            ReturnCode_t return_code_names {eprosima::fastdds::dds::RETCODE_OK};
            return_code_names =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_anonymous_string_unbounded_unbounded", type_ids_names);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_names)
            {
                return_code_names =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "anonymous_string_unbounded", type_ids_names);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_names)
                {
                    {
                        SBound bound = 0;
                        StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                                TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                                "anonymous_string_unbounded", type_ids_names))
                        {
                            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                                "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                        }
                    }
                }
                bool element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_names, element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_anonymous_string_unbounded_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_names.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_anonymous_string_unbounded_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_anonymous_string_unbounded_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_anonymous_string_unbounded_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_anonymous_string_unbounded_unbounded, element_flags_anonymous_sequence_anonymous_string_unbounded_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_anonymous_string_unbounded_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_anonymous_string_unbounded_unbounded", type_ids_names))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_anonymous_string_unbounded_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_names = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_names = 0x00000000;
            bool common_names_ec {false};
            CommonStructMember common_names {TypeObjectUtils::build_common_struct_member(member_id_names, member_flags_names, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_names, common_names_ec))};
            if (!common_names_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure names member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_names = "names";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_names;
            ann_custom_GetParameters_Request.reset();
            CompleteMemberDetail detail_names = TypeObjectUtils::build_complete_member_detail(name_names, member_ann_builtin_names, ann_custom_GetParameters_Request);
            CompleteStructMember member_names = TypeObjectUtils::build_complete_struct_member(common_names, detail_names);
            TypeObjectUtils::add_complete_struct_member(member_seq_GetParameters_Request, member_names);
        }
        CompleteStructType struct_type_GetParameters_Request = TypeObjectUtils::build_complete_struct_type(struct_flags_GetParameters_Request, header_GetParameters_Request, member_seq_GetParameters_Request);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_GetParameters_Request, type_name_GetParameters_Request.to_string(), type_ids_GetParameters_Request))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "rcl_interfaces::srv::GetParameters_Request already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_GetParameters_Response_type_identifier(
        TypeIdentifierPair& type_ids_GetParameters_Response)
{

    ReturnCode_t return_code_GetParameters_Response {eprosima::fastdds::dds::RETCODE_OK};
    return_code_GetParameters_Response =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "rcl_interfaces::srv::GetParameters_Response", type_ids_GetParameters_Response);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_GetParameters_Response)
    {
        StructTypeFlag struct_flags_GetParameters_Response = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_GetParameters_Response = "rcl_interfaces::srv::GetParameters_Response";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_GetParameters_Response;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_GetParameters_Response;
        CompleteTypeDetail detail_GetParameters_Response = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_GetParameters_Response, ann_custom_GetParameters_Response, type_name_GetParameters_Response.to_string());
        CompleteStructHeader header_GetParameters_Response;
        header_GetParameters_Response = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_GetParameters_Response);
        CompleteStructMemberSeq member_seq_GetParameters_Response;
        {
            TypeIdentifierPair type_ids_values;
            ReturnCode_t return_code_values {eprosima::fastdds::dds::RETCODE_OK};
            return_code_values =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded", type_ids_values);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_values)
            {
                return_code_values =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "rcl_interfaces::msg::ParameterValue", type_ids_values);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_values)
                {
                    rcl_interfaces::msg::register_ParameterValue_type_identifier(type_ids_values);
                }
                bool element_identifier_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_values, element_identifier_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_values.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded, element_flags_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded", type_ids_values))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_rcl_interfaces_msg_ParameterValue_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_values = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_values = 0x00000000;
            bool common_values_ec {false};
            CommonStructMember common_values {TypeObjectUtils::build_common_struct_member(member_id_values, member_flags_values, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_values, common_values_ec))};
            if (!common_values_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure values member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_values = "values";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_values;
            ann_custom_GetParameters_Response.reset();
            CompleteMemberDetail detail_values = TypeObjectUtils::build_complete_member_detail(name_values, member_ann_builtin_values, ann_custom_GetParameters_Response);
            CompleteStructMember member_values = TypeObjectUtils::build_complete_struct_member(common_values, detail_values);
            TypeObjectUtils::add_complete_struct_member(member_seq_GetParameters_Response, member_values);
        }
        CompleteStructType struct_type_GetParameters_Response = TypeObjectUtils::build_complete_struct_type(struct_flags_GetParameters_Response, header_GetParameters_Response, member_seq_GetParameters_Response);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_GetParameters_Response, type_name_GetParameters_Response.to_string(), type_ids_GetParameters_Response))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "rcl_interfaces::srv::GetParameters_Response already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace srv

} // namespace rcl_interfaces

