// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AddTwoInts_Response.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__EXAMPLE_INTERFACES_SRV_ADDTWOINTS_RESPONSE_HPP
#define FAST_DDS_GENERATED__EXAMPLE_INTERFACES_SRV_ADDTWOINTS_RESPONSE_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ADDTWOINTS_RESPONSE_SOURCE)
#define ADDTWOINTS_RESPONSE_DllAPI __declspec( dllexport )
#else
#define ADDTWOINTS_RESPONSE_DllAPI __declspec( dllimport )
#endif // ADDTWOINTS_RESPONSE_SOURCE
#else
#define ADDTWOINTS_RESPONSE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ADDTWOINTS_RESPONSE_DllAPI
#endif // _WIN32

namespace example_interfaces {

namespace srv {

/*!
 * @brief This class represents the structure AddTwoInts_Response defined by the user in the IDL file.
 * @ingroup AddTwoInts_Response
 */
class AddTwoInts_Response
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport AddTwoInts_Response()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~AddTwoInts_Response()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object AddTwoInts_Response that will be copied.
     */
    eProsima_user_DllExport AddTwoInts_Response(
            const AddTwoInts_Response& x)
    {
                    m_sum = x.m_sum;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object AddTwoInts_Response that will be copied.
     */
    eProsima_user_DllExport AddTwoInts_Response(
            AddTwoInts_Response&& x) noexcept
    {
        m_sum = x.m_sum;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object AddTwoInts_Response that will be copied.
     */
    eProsima_user_DllExport AddTwoInts_Response& operator =(
            const AddTwoInts_Response& x)
    {

                    m_sum = x.m_sum;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object AddTwoInts_Response that will be copied.
     */
    eProsima_user_DllExport AddTwoInts_Response& operator =(
            AddTwoInts_Response&& x) noexcept
    {

        m_sum = x.m_sum;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x AddTwoInts_Response object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const AddTwoInts_Response& x) const
    {
        return (m_sum == x.m_sum);
    }

    /*!
     * @brief Comparison operator.
     * @param x AddTwoInts_Response object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const AddTwoInts_Response& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member sum
     * @param _sum New value for member sum
     */
    eProsima_user_DllExport void sum(
            int64_t _sum)
    {
        m_sum = _sum;
    }

    /*!
     * @brief This function returns the value of member sum
     * @return Value of member sum
     */
    eProsima_user_DllExport int64_t sum() const
    {
        return m_sum;
    }

    /*!
     * @brief This function returns a reference to member sum
     * @return Reference to member sum
     */
    eProsima_user_DllExport int64_t& sum()
    {
        return m_sum;
    }



private:

    int64_t m_sum{0};

};

} // namespace srv

} // namespace example_interfaces

#endif // _FAST_DDS_GENERATED_EXAMPLE_INTERFACES_SRV_ADDTWOINTS_RESPONSE_HPP_


